fix: add retry

diff --git a/.github/workflows/docker-banking.yml b/.github/workflows/docker-banking.yml
--- a/.github/workflows/docker-banking.yml
+++ b/.github/workflows/docker-banking.yml
@@ -80,22 +80,36 @@ jobs:
     - name: Fetch data and check httpPercentReq
       run: |
         URL="http://${{ secrets.KIALI_SERVER_IP }}/kiali/api/namespaces/default/workloads/banking-deployment-canary/graph?duration=120s&graphType=workload&responseTime=95&appenders=responseTime,throughput&rateHttp=requests"
-        RESPONSE=$(curl -s "$URL")
+        # Initialize retry count
+        MAX_RETRIES=5
+        count=0
+        
+        while [ $count -lt $MAX_RETRIES ]; do
+          RESPONSE=$(curl -s "$URL")
+          echo "Response: $RESPONSE"  # Echo the response from server for debugging
+        
+          # Check if the response is not empty and contains expected data
+          if [[ ! -z "$RESPONSE" && "$(echo $RESPONSE | jq '.elements')" != "null" ]]; then
+            echo "Successfully fetched data"
+            break
+          else
+            echo "Failed to fetch data, attempting retry $((count + 1))"
+            ((count++))
+            sleep 5  # Wait for 5 seconds before retrying
+          fi
+        done
+        
+        if [ $count -eq $MAX_RETRIES ]; then
+          echo "Failed after $MAX_RETRIES attempts."
+          exit 1
+        fi
+        
+        # Parse the response to get HTTP percent request rate
         HTTP_PERCENT_REQ=$(echo $RESPONSE | jq '.elements.edges[] | select(.data.target | select(.workload == "banking-deployment-canary" and .namespace == "default")).data.traffic.rates.httpPercentReq | tonumber')
         echo "HTTP Percent Request: $HTTP_PERCENT_REQ"
-
+        
         if (( $(echo "$HTTP_PERCENT_REQ > 98" | bc -l) )); then
           echo "Result: true"
         else
           echo "Result: false"
         fi
-
-    - name: Set result as output
-      id: check_result
-      run: |
-        RESULT=$(echo "Result: false")
-        echo "::set-output name=result::$RESULT"
-
-    - name: Use the output
-      run: echo "The result of HTTP Percent Request Check is ${{ steps.check_result.outputs.result }}"
-  
